### PR TITLE
fixed change lol

### PR DESCRIPTION
**Pull request by TheBruschettaBrother**
sorry for the shittty nav

### CODE REVIEW

**Review by HSCorp99906 — CHANGES_REQUESTED** [review]
Please again.. Limit to one hyperlink to repo.

**Comment by DoomLibreGuy** [comment]
i swear i did

**Comment by HSCorp99906** [comment]
Weird glitch sorry, I fixed it.

**Review by HSCorp99906 — APPROVED** [review]
:+1:

**Pull request merged**
