### PR TITLE
BIG HTML CHANGE

### PR DESCRIPTION
**Pull request by TheBruschettaBrother**
added a nav and a article to section things up and after this i will add more payment widgets and sections

### CODE REVIEW

**Comment by TheBruschettaBrother** [comment]
hoho merry chrisma u have bootyful html now

**Comment by HSCorp99906** [comment]
Ah, thank you. I shall review it now.

**Comment by HSCorp99906** [comment]
Question @DoomLibreGuy.

**Review by HSCorp99906 — CHANGES_REQUESTED** [review]
Please just have one hyperlink.

**Comment by HSCorp99906** [comment]
Actually just redo your commit.

**Pull request closed without merging**
