### PR TITLE
2nd logo upload

### PR DESCRIPTION
**Pull request by TheBruschettaBrother**
plz accpet im adding a the 2nd logo

### CODE REVIEW

**Review by HSCorp99906 — CHANGES_REQUESTED** [review]
This is a little too blue for my eyes, it hurts AHHHH MY EYES I AM GONNA SUE YOU AHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH MY EYES!!!! LAWYER!!! 


But seriously, please make it less blue.

**Comment by HSCorp99906** [comment]
Nevermind don't change it.

**Comment by TheBruschettaBrother** [comment]
penis

**Comment by HSCorp99906** [comment]
We keep our logo.

**Comment by HSCorp99906** [comment]
> penis

I am sorry, WHAT?

**Comment by TheBruschettaBrother** [comment]
bull penis

**Comment by HSCorp99906** [comment]
NO.

**Comment by HSCorp99906** [comment]
S T O P.

**Comment by TheBruschettaBrother** [comment]
sorry

**Comment by TheBruschettaBrother** [comment]
please dont fire me i have 3 kids to feed

**Comment by HSCorp99906** [comment]
:triumph:

**Comment by TheBruschettaBrother** [comment]
im joking u cant fire me

**Comment by TheBruschettaBrother** [comment]
cuz we started it

**Comment by HSCorp99906** [comment]
**Wrong**. My cat started it.

**Pull request closed without merging**
